/*
 * Generated by ChatGPT
 * 
 * Based on: https://bottosson.github.io/posts/oklab/
 * Björn Ottosson.
 * "A perceptual color space for image processing"
 */

using System.Runtime.CompilerServices;

namespace ColorForge.Core;

/// <summary>
/// Performs conversions between supported color spaces.
/// </summary>
public static class ColorConverter {
    #region Public API

    /// <summary>
    /// Converts an sRGB color into linear RGB.
    /// </summary>
    public static LinearRgbColor ToLinearRgb(
        ThemeColor color) {
        return new LinearRgbColor(
            SrgbToLinear(color.R),
            SrgbToLinear(color.G),
            SrgbToLinear(color.B));
    }

    /// <summary>
    /// Converts a linear RGB color into an sRGB color.
    /// </summary>
    public static ThemeColor FromLinearRgb(
        LinearRgbColor color) {
        color = color.Clamp();

        return ThemeColor.FromArgb(
            255,
            LinearToSrgb(color.R),
            LinearToSrgb(color.G),
            LinearToSrgb(color.B));
    }

    #endregion

    #region Gamma

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    internal static double SrgbToLinear(byte component) {
        double value = component / 255.0;

        if (value <= ColorSpaceConstants.SrgbGammaThreshold) {
            return value *
                   ColorSpaceConstants.InverseGammaSlope;
        }

        return Math.Pow(
            (value + ColorSpaceConstants.GammaOffset)
                * ColorSpaceConstants.InverseGammaScale,
            ColorSpaceConstants.GammaExponent);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    internal static byte LinearToSrgb(double component) {
        component = Math.Clamp(component, 0.0, 1.0);

        double value;

        if (component <= ColorSpaceConstants.LinearGammaThreshold) {
            value =
                component *
                ColorSpaceConstants.GammaSlope;
        } else {
            value =
                ColorSpaceConstants.GammaScale *
                Math.Pow(
                    component,
                    ColorSpaceConstants.InverseGammaExponent)
                - ColorSpaceConstants.GammaOffset;
        }

        return (byte)Math.Round(
            value * 255.0,
            MidpointRounding.AwayFromZero);
    }

    #endregion

    #region Linear RGB -> XYZ

    /// <summary>
    /// Converts a linear sRGB color into CIE XYZ (D65).
    /// </summary>
    public static XyzColor ToXyz(LinearRgbColor color) {
        double r = color.R;
        double g = color.G;
        double b = color.B;

        return new XyzColor(
            x: 0.4124564 * r +
               0.3575761 * g +
               0.1804375 * b,

            y: 0.2126729 * r +
               0.7151522 * g +
               0.0721750 * b,

            z: 0.0193339 * r +
               0.1191920 * g +
               0.9503041 * b);
    }

    #endregion

    #region XYZ -> Linear RGB

    /// <summary>
    /// Converts a CIE XYZ (D65) color into linear sRGB.
    /// </summary>
    public static LinearRgbColor FromXyz(XyzColor xyz) {
        double x = xyz.X;
        double y = xyz.Y;
        double z = xyz.Z;

        double r =
              3.2404542 * x
           - 1.5371385 * y
           - 0.4985314 * z;

        double g =
            -0.9692660 * x
           + 1.8760108 * y
           + 0.0415560 * z;

        double b =
            0.0556434 * x
           - 0.2040259 * y
           + 1.0572252 * z;

        return new LinearRgbColor(r, g, b);
    }

    #endregion

    #region Linear RGB <-> OKLab

    /// <summary>
    /// Converts a linear sRGB color to OKLab.
    /// </summary>
    public static OklabColor ToOklab(LinearRgbColor rgb) {
        // RGB -> LMS

        //TODO : migrer la matrice de conversion vers ColorSpaceConstants

        double l =
            0.4122214708 * rgb.R +
            0.5363325363 * rgb.G +
            0.0514459929 * rgb.B;

        double m =
            0.2119034982 * rgb.R +
            0.6806995451 * rgb.G +
            0.1073969566 * rgb.B;

        double s =
            0.0883024619 * rgb.R +
            0.2817188376 * rgb.G +
            0.6299787005 * rgb.B;

        // Non-linear transform

        double l_ = Math.Cbrt(l);
        double m_ = Math.Cbrt(m);
        double s_ = Math.Cbrt(s);

        //TODO : migrer la matrice de conversion vers ColorSpaceConstants

        return new OklabColor(

            l:
                0.2104542553 * l_ +
                0.7936177850 * m_ -
                0.0040720468 * s_,

            a:
                1.9779984951 * l_ -
                2.4285922050 * m_ +
                0.4505937099 * s_,

            b:
                0.0259040371 * l_ +
                0.7827717662 * m_ -
                0.8086757660 * s_);
    }

    /// <summary>
    /// ToOklab
    /// </summary>
    /// <param name="color"></param>
    /// <returns></returns>
    public static OklabColor ToOklab(ThemeColor color) {
        return ToOklab(ToLinearRgb(color));
    }


    /// <summary>
    /// Converts an OKLab color to linear sRGB.
    /// </summary>
    public static LinearRgbColor FromOklab(OklabColor lab) {

        //TODO : migrer la matrice de conversion vers ColorSpaceConstants

        double l_ =
            lab.L +
            0.3963377774 * lab.A +
            0.2158037573 * lab.B;

        double m_ =
            lab.L -
            0.1055613458 * lab.A -
            0.0638541728 * lab.B;

        double s_ =
            lab.L -
            0.0894841775 * lab.A -
            1.2914855480 * lab.B;

        double l = l_ * l_ * l_;
        double m = m_ * m_ * m_;
        double s = s_ * s_ * s_;

        //TODO : migrer la matrice de conversion vers ColorSpaceConstants

        return new LinearRgbColor(

            r:
                 4.0767416621 * l
               - 3.3077115913 * m
               + 0.2309699292 * s,

            g:
               -1.2684380046 * l
               + 2.6097574011 * m
               - 0.3413193965 * s,

            b:
               -0.0041960863 * l
               - 0.7034186147 * m
               + 1.7076147010 * s);
    }

    /// <summary>
    /// ThemeColorFromOklab
    /// </summary>
    /// <param name="color"></param>
    /// <returns></returns>
    public static ThemeColor ThemeColorFromOklab(OklabColor color) {
        return FromLinearRgb(
            FromOklab(color));
    }

    #endregion
}