/*
 * Generated by ChatGPT
 */

/// <summary>
/// ColorSpace
/// </summary>
public enum ColorSpace {
    /// <summary>
    /// RGB
    /// </summary>
    Rgb,
    /// <summary>
    /// XYZ
    /// </summary>
    Xyz,
    /// <summary>
    /// Oklab
    /// </summary>
    Oklab,
    /// <summary>
    /// Oklch
    /// </summary>
    Oklch
}