/*
 * Generated by ChatGPT
 */

using System.Runtime.CompilerServices;

namespace ColorForge.Core;

/// <summary>
/// Mathematical helpers used throughout ColorForge.
/// </summary>
public static class ColorMath {
    /// <summary>
    /// Clamps a value between 0 and 1.
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static double Clamp01(double value) {
        return Math.Clamp(value, 0d, 1d);
    }

    /// <summary>
    /// Clamps a value.
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static double Clamp(
        double value,
        double min,
        double max) {
        return Math.Clamp(value, min, max);
    }

    /// <summary>
    /// Linearly interpolates between two values.
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static double Lerp(
        double a,
        double b,
        double t) {
        return a + (b - a) * t;
    }

    /// <summary>
    /// Performs inverse linear interpolation.
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static double InverseLerp(
        double a,
        double b,
        double value) {
        if (a == b) {
            return 0;
        }

        return (value - a) / (b - a);
    }

    /// <summary>
    /// Remaps a value from one interval to another.
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static double Remap(
        double value,
        double sourceMin,
        double sourceMax,
        double targetMin,
        double targetMax) {
        return Lerp(
            targetMin,
            targetMax,
            InverseLerp(
                sourceMin,
                sourceMax,
                value));
    }
}