/*
 * Generated by ChatGPT
 * 
 * Based on :
 * IEC 61966-2-1
 * CIE 1931
 * CSS Color Module Level 4
 * Bruce Lindbloom's work
 * Björn Ottosson's work
 */

using System.Runtime.CompilerServices;

namespace ColorForge.Core;

/// <summary>
/// Mathematical constants used by the color conversion pipeline.
///
/// These values are based on the official OKLab specification
/// by Björn Ottosson and the IEC 61966-2-1 sRGB standard.
/// </summary>
internal static class ColorSpaceConstants {

    #region RGB
    public const double RgbWhiteR = 1;
    public const double RgbWhiteG = 1;
    public const double RgbWhiteB = 1;

    public const double RgbPureRedR = 1;
    public const double RgbPureRedG = 0;
    public const double RgbPureRedB = 0;
    #endregion

    #region sRGB gamma

    /// <summary>
    /// sRGB gamma breakpoint.
    /// </summary>
    public const double SrgbGammaThreshold = 0.04045;

    /// <summary>
    /// Inverse sRGB gamma breakpoint.
    /// </summary>
    public const double LinearGammaThreshold = 0.0031308;

    /// <summary>
    /// 1 / 12.92
    /// </summary>
    public const double InverseGammaSlope = 1.0 / 12.92;

    /// <summary>
    /// 12.92
    /// </summary>
    public const double GammaSlope = 12.92;

    /// <summary>
    /// 1 / 1.055
    /// </summary>
    public const double InverseGammaScale = 1.0 / 1.055;

    /// <summary>
    /// 1.055
    /// </summary>
    public const double GammaScale = 1.055;

    /// <summary>
    /// 0.055
    /// </summary>
    public const double GammaOffset = 0.055;

    /// <summary>
    /// sRGB exponent.
    /// </summary>
    public const double GammaExponent = 2.4;

    /// <summary>
    /// Inverse sRGB exponent.
    /// </summary>
    public const double InverseGammaExponent = 1.0 / 2.4;

    #endregion

    #region D65
    public const double D65WhiteX = 0.95047;
    public const double D65WhiteY = 1.00000;
    public const double D65WhiteZ = 1.08883;
    #endregion

    //TODO : Déplacer ici toutes les constantes utilisées dans "ColorForge.Core"

    #region Helpers

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static double Cube(double value) {
        return value * value * value;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static double CubeRoot(double value) {
        return Math.Cbrt(value);
    }

    #endregion


}