/*
 * Generated by ChatGPT
 */

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ColorForge.Core {
    internal interface IColorVector3 {
        double X {
            get;
        }

        double Y {
            get;
        }

        double Z {
            get;
        }
    }
}
