/*
 * Generated by ChatGPT
 */

using System.Diagnostics;
using System.Globalization;
using System.Runtime.CompilerServices;

namespace ColorForge.Core;

/// <summary>
/// Represents a color in the linear sRGB color space.
/// </summary>
/// <remarks>
/// <para>
/// Contrary to <see cref="ThemeColor"/>, this color space is not gamma corrected.
/// </para>
/// <para>
/// It is the intermediate representation used for:
/// <list type="bullet">
/// <item>RGB ↔ XYZ conversion</item>
/// <item>Physical color interpolation</item>
/// <item>Alpha compositing</item>
/// <item>Gradient generation</item>
/// </list>
/// </para>
/// </remarks>
[DebuggerDisplay("R={R}, G={G}, B={B}")]
public readonly record struct LinearRgbColor {

    /// <summary>
    /// MaxComponent
    /// </summary>
    public double MaxComponent {
        get;
    }

    /// <summary>
    /// MinComponent
    /// </summary>
    public double MinComponent {
        get;
    }

    /// <summary>
    /// AverageComponent
    /// </summary>
    public double AverageComponent {
        get;
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="LinearRgbColor"/> struct.
    /// </summary>
    public LinearRgbColor(
        double r,
        double g,
        double b) {
        R = r;
        G = g;
        B = b;
    }

    /// <summary>
    /// Gets the red component.
    /// </summary>
    public double R {
        get;
    }

    /// <summary>
    /// Gets the green component.
    /// </summary>
    public double G {
        get;
    }

    /// <summary>
    /// Gets the blue component.
    /// </summary>
    public double B {
        get;
    }

    /// <summary>
    /// Gets whether all components are finite.
    /// </summary>
    public bool IsValid {
        get {
            return double.IsFinite(R) &&
        double.IsFinite(G) &&
        double.IsFinite(B);
        }
    }

    /// <summary>
    /// Gets whether every component lies in the standard gamut.
    /// </summary>
    public bool IsInGamut {
        get {
            return R is >= 0 and <= 1 &&
        G is >= 0 and <= 1 &&
        B is >= 0 and <= 1;
        }
    }

    /// <summary>
    /// Returns a clamped version of this color.
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public LinearRgbColor Clamp() {
        return new(
            Clamp01(R),
            Clamp01(G),
            Clamp01(B));
    }

    /// <summary>
    /// Returns a copy with a different red component.
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public LinearRgbColor WithRed(double value) {
        return new(value, G, B);
    }

    /// <summary>
    /// Returns a copy with a different green component.
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public LinearRgbColor WithGreen(double value) {
        return new(R, value, B);
    }

    /// <summary>
    /// Returns a copy with a different blue component.
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public LinearRgbColor WithBlue(double value) {
        return new(R, G, value);
    }

    /// <inheritdoc/>
    public override string ToString() {
        return string.Create(
            CultureInfo.InvariantCulture,
            $"R={R:F6}, G={G:F6}, B={B:F6}");
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static double Clamp01(double value) {
        if (value < 0) {
            return 0;
        }

        if (value > 1) {
            return 1;
        }

        return value;
    }
}