/*
 * Generated by ChatGPT
 */

using System.Globalization;

namespace ColorForge.Core;

/// <summary>
/// Represents a color in the OKLab color space.
/// </summary>
/// <remarks>
/// <para>
/// OKLab is a perceptually uniform color space designed by Björn Ottosson.
/// It provides visually consistent interpolation and lightness adjustments.
/// </para>
/// <para>
/// Component ranges are typically:
/// <list type="bullet">
/// <item><description>L : 0.0 → 1.0</description></item>
/// <item><description>A : approximately -0.4 → +0.4</description></item>
/// <item><description>B : approximately -0.4 → +0.4</description></item>
/// </list>
/// The A and B ranges are not clamped because valid values depend on the
/// destination color gamut.
/// </para>
/// </remarks>
public readonly record struct OklabColor {
    /// <summary>
    /// Initializes a new instance of the <see cref="OklabColor"/> struct.
    /// </summary>
    /// <param name="l">Perceptual lightness.</param>
    /// <param name="a">Green-red axis.</param>
    /// <param name="b">Blue-yellow axis.</param>
    public OklabColor(double l, double a, double b) {
        L = l;
        A = a;
        B = b;
    }

    /// <summary>
    /// Gets the perceptual lightness.
    /// </summary>
    public double L {
        get;
    }

    /// <summary>
    /// Gets the green-red axis.
    /// </summary>
    public double A {
        get;
    }

    /// <summary>
    /// Gets the blue-yellow axis.
    /// </summary>
    public double B {
        get;
    }

    /// <summary>
    /// Returns true when all components are finite.
    /// </summary>
    public bool IsValid {
        get {
            return double.IsFinite(L) &&
        double.IsFinite(A) &&
        double.IsFinite(B);
        }
    }

    /// <summary>
    /// Returns a copy with a different lightness.
    /// </summary>
    public OklabColor WithLightness(double lightness) {
        return new(lightness, A, B);
    }

    /// <summary>
    /// Returns a copy with a different A component.
    /// </summary>
    public OklabColor WithA(double a) {
        return new(L, a, B);
    }

    /// <summary>
    /// Returns a copy with a different B component.
    /// </summary>
    public OklabColor WithB(double b) {
        return new(L, A, b);
    }

    /// <inheritdoc/>
    public override string ToString() {
        return string.Create(
            CultureInfo.InvariantCulture,
            $"L={L:F6}, A={A:F6}, B={B:F6}");
    }
}