/*
 * Generated by ChatGPT
 */

using System.Globalization;

namespace ColorForge.Core;

/// <summary>
/// Represents a color in the OKLCH color space.
/// </summary>
/// <remarks>
/// <para>
/// OKLCH is the cylindrical representation of the OKLab color space.
/// It is especially well suited for perceptual color manipulation such as
/// generating tonal palettes, adjusting chroma or rotating hue.
/// </para>
/// <para>
/// Component ranges are typically:
/// <list type="bullet">
/// <item><description>L : 0.0 → 1.0</description></item>
/// <item><description>C : 0.0 → approximately 0.4</description></item>
/// <item><description>H : 0.0 → 360.0 degrees</description></item>
/// </list>
/// </para>
/// </remarks>
public readonly record struct OklchColor {
    /// <summary>
    /// Initializes a new instance of the <see cref="OklchColor"/> struct.
    /// </summary>
    /// <param name="l">Perceptual lightness.</param>
    /// <param name="c">Perceptual chroma.</param>
    /// <param name="h">Hue angle in degrees.</param>
    public OklchColor(
        double l,
        double c,
        double h) {
        L = l;
        C = c;
        H = NormalizeHue(h);
    }

    /// <summary>
    /// Gets the perceptual lightness.
    /// </summary>
    public double L {
        get;
    }

    /// <summary>
    /// Gets the perceptual chroma.
    /// </summary>
    public double C {
        get;
    }

    /// <summary>
    /// Gets the hue angle in degrees.
    /// </summary>
    public double H {
        get;
    }

    /// <summary>
    /// Gets a value indicating whether this instance contains finite values.
    /// </summary>
    public bool IsValid {
        get {
            return double.IsFinite(L) &&
        double.IsFinite(C) &&
        double.IsFinite(H);
        }
    }

    /// <summary>
    /// Returns a copy with a different lightness.
    /// </summary>
    public OklchColor WithLightness(double lightness) {
        return new(lightness, C, H);
    }

    /// <summary>
    /// Returns a copy with a different chroma.
    /// </summary>
    public OklchColor WithChroma(double chroma) {
        return new(L, chroma, H);
    }

    /// <summary>
    /// Returns a copy with a different hue.
    /// </summary>
    public OklchColor WithHue(double hue) {
        return new(L, C, hue);
    }

    /// <summary>
    /// Rotates the hue by the specified number of degrees.
    /// </summary>
    public OklchColor RotateHue(double degrees) {
        return new(L, C, H + degrees);
    }

    /// <inheritdoc/>
    public override string ToString() {
        return string.Create(
            CultureInfo.InvariantCulture,
            $"L={L:F6}, C={C:F6}, H={H:F3}°");
    }

    private static double NormalizeHue(double hue) {
        hue %= 360.0;

        if (hue < 0) {
            hue += 360.0;
        }

        return hue;
    }
}