/*
 * Generated by ChatGPT
 */

namespace ColorForge.Core;

public readonly partial struct ThemeColor
{
    /// <summary>
    /// ToRgbHex
    /// </summary>
    public string ToRgbHex() {
        return $"#{R:X2}{G:X2}{B:X2}";
    }

    /// <summary>
    /// ToArgbHex
    /// </summary>
    public string ToArgbHex() {
        return $"#{A:X2}{R:X2}{G:X2}{B:X2}";
    }

    /// <summary>
    /// ToString
    /// </summary>
    public override string ToString() {
        return ToArgbHex();
    }
}