/*
 * Generated by ChatGPT
 */

namespace ColorForge.Core {

    /// <summary>
    /// Represents an immutable RGBA color.
    /// </summary>
    public readonly partial struct ThemeColor :
        IEquatable<ThemeColor> {

        /// <summary>
        /// R
        /// </summary>
        public byte R {
            get;
        }

        /// <summary>
        /// Red
        /// </summary>
        public double Red {
            get {
                return R / 255.0;
            }
        }

        /// <summary>
        /// G
        /// </summary>
        public byte G {
            get;
        }

        /// <summary>
        /// Green
        /// </summary>
        public double Green {
            get {
                return G / 255.0;
            }
        }

        /// <summary>
        /// B
        /// </summary>
        public byte B {
            get;
        }


        /// <summary>
        /// Blue
        /// </summary>
        public double Blue {
            get {
                return B / 255.0;
            }
        }

        /// <summary>
        /// A
        /// </summary>
        public byte A {
            get;
        }

        /// <summary>
        /// ThemeColor
        /// </summary>
        public ThemeColor(
            byte r,
            byte g,
            byte b,
            byte a = 255) {
            R = r;
            G = g;
            B = b;
            A = a;
        }

        /// <summary>
        /// Deconstruct
        /// </summary>
        public void Deconstruct(
            out byte r,
            out byte g,
            out byte b,
            out byte a) {
            r = R;
            g = G;
            b = B;
            a = A;
        }
    }
}