/*
 * Generated by ChatGPT
 */

namespace ColorForge.Core;

public readonly partial struct ThemeColor {

    /// <summary>
    /// FromRgb
    /// </summary>
    public static ThemeColor FromRgb(
        byte r,
        byte g,
        byte b) {
        return new(r, g, b);
    }

    /// <summary>
    /// FromArgb
    /// </summary>
    public static ThemeColor FromArgb(
        byte a,
        byte r,
        byte g,
        byte b) {
        return new(r, g, b, a);
    }

    /// <summary>
    /// FromHex
    /// </summary>
    public static ThemeColor FromHex(string hex) {
        ArgumentNullException.ThrowIfNull(hex);

        hex = hex.Trim();

        if (hex.StartsWith('#')) {
            hex = hex[1..];
        }

        return hex.Length switch {
            6 => new ThemeColor(
                Convert.ToByte(hex[0..2], 16),
                Convert.ToByte(hex[2..4], 16),
                Convert.ToByte(hex[4..6], 16)),

            8 => new ThemeColor(
                Convert.ToByte(hex[2..4], 16),
                Convert.ToByte(hex[4..6], 16),
                Convert.ToByte(hex[6..8], 16),
                Convert.ToByte(hex[0..2], 16)),

            _ => throw new FormatException(
                "Hex color must be #RRGGBB or #AARRGGBB.")
        };
    }
}