/*
 * Generated by ChatGPT
 */

namespace ColorForge.Core;

public readonly partial struct ThemeColor {

    /// <summary>
    /// Equals
    /// </summary>
    public bool Equals(ThemeColor other) {
        return
            R == other.R &&
            G == other.G &&
            B == other.B &&
            A == other.A;
    }

    /// <summary>
    /// Equals
    /// </summary>
    public override bool Equals(object? obj) {
        return obj is ThemeColor c && Equals(c);
    }

    /// <summary>
    /// GetHashCode
    /// </summary>
    public override int GetHashCode() {
        return HashCode.Combine(R, G, B, A);
    }

    /// <summary>
    /// Equality
    /// </summary>
    public static bool operator ==(
        ThemeColor left,
        ThemeColor right)
        => left.Equals(right);

    /// <summary>
    /// Inequality
    /// </summary>
    public static bool operator !=(
        ThemeColor left,
        ThemeColor right)
        => !left.Equals(right);
}