/*
 * Generated by ChatGPT
 */

using System.Collections;
using System.Collections.ObjectModel;

namespace ColorForge.Core;

/// <summary>
/// Represents a perceptual tonal palette.
/// </summary>
public sealed class TonalPalette :
    IReadOnlyList<ThemeColor> {
    private readonly ThemeColor[] _colors;
    private readonly int[] _tones;

    internal TonalPalette(
        int[] tones,
        ThemeColor[] colors) {
        ArgumentNullException.ThrowIfNull(tones);
        ArgumentNullException.ThrowIfNull(colors);

        if (tones.Length != colors.Length) {
            throw new ArgumentException(
                "Tone and color counts must match.");
        }

        _tones = tones;
        _colors = colors;
    }

    /// <summary>
    /// Gets the number of tones.
    /// </summary>
    public int Count {
        get {
            return _colors.Length;
        }
    }

    /// <summary>
    /// Gets the color at the specified index.
    /// </summary>
    public ThemeColor this[int index]
        => _colors[index];

    /// <summary>
    /// Gets the color for a given tone.
    /// </summary>
    public ThemeColor GetTone(int tone) {
        int index = Array.BinarySearch(
            _tones,
            tone);

        if (index < 0) {
            throw new ArgumentOutOfRangeException(
                nameof(tone));
        }

        return _colors[index];
    }

    /// <summary>
    /// Gets all available tones.
    /// </summary>
    public ReadOnlyCollection<int> Tones {
        get {
            return Array.AsReadOnly(_tones);
        }
    }

    /// <summary>
    /// GetEnumerator
    /// </summary>
    /// <returns></returns>
    public IEnumerator<ThemeColor> GetEnumerator() {
        return ((IEnumerable<ThemeColor>)_colors).GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator() {
        return GetEnumerator();
    }
}