/*
 * Generated by ChatGPT
 */

/// <summary>
/// Tone
/// </summary>
public readonly record struct Tone {
    /// <summary>
    /// Value
    /// </summary>
    public int Value {
        get;
    }
}