/*
 * Generated by ChatGPT
 */

using System.Diagnostics;
using System.Globalization;
using System.Runtime.CompilerServices;

namespace ColorForge.Core;

/// <summary>
/// Represents a color in the CIE XYZ color space (D65).
/// </summary>
/// <remarks>
/// <para>
/// CIE XYZ is the device-independent connection space used by the
/// ColorForge conversion pipeline.
///
/// ThemeColor
///     ↓
/// LinearRgbColor
///     ↓
/// XyzColor
///     ↓
/// OklabColor
///     ↓
/// OklchColor
/// </para>
/// </remarks>
[DebuggerDisplay("X={X}, Y={Y}, Z={Z}")]
public readonly record struct XyzColor {
    /// <summary>
    /// Initializes a new XYZ color.
    /// </summary>
    public XyzColor(
        double x,
        double y,
        double z) {
        X = x;
        Y = y;
        Z = z;
    }

    /// <summary>
    /// Gets the X tristimulus component.
    /// </summary>
    public double X {
        get;
    }

    /// <summary>
    /// Gets the Y tristimulus component.
    /// </summary>
    public double Y {
        get;
    }

    /// <summary>
    /// Gets the Z tristimulus component.
    /// </summary>
    public double Z {
        get;
    }

    /// <summary>
    /// Gets whether all components are finite.
    /// </summary>
    public bool IsValid {
        get {
            return double.IsFinite(X) &&
        double.IsFinite(Y) &&
        double.IsFinite(Z);
        }
    }

    /// <summary>
    /// Returns a copy with another X value.
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public XyzColor WithX(double value) {
        return new(value, Y, Z);
    }

    /// <summary>
    /// Returns a copy with another Y value.
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public XyzColor WithY(double value) {
        return new(X, value, Z);
    }

    /// <summary>
    /// Returns a copy with another Z value.
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public XyzColor WithZ(double value) {
        return new(X, Y, value);
    }

    /// <inheritdoc/>
    public override string ToString() {
        return string.Create(
            CultureInfo.InvariantCulture,
            $"X={X:F6}, Y={Y:F6}, Z={Z:F6}");
    }
}