/*
 * Generated by ChatGPT
 */

using ColorForge.Core;

public sealed class ColorMathTests {

    [Fact]
    public void Clamp01_Should_Work() {

        AssertEx.NearlyEqual(0, ColorMath.Clamp01(-2));

        AssertEx.NearlyEqual(0.5, ColorMath.Clamp01(.5));

        AssertEx.NearlyEqual(1, ColorMath.Clamp01(5));
    }
    
    [Fact]
    public void Lerp_Should_Work() {
        AssertEx.NearlyEqual(
            5,
            ColorMath.Lerp(0, 10, .5));
    }
    
    [Fact]
    public void InverseLerp_Should_Work() {
        AssertEx.NearlyEqual(
            .5,
            ColorMath.InverseLerp(
                10,
                20,
                15));
    }
    
    [Fact]
    public void Remap_Should_Work() {
        AssertEx.NearlyEqual(
            50,
            ColorMath.Remap(
                .5,
                0,
                1,
                0,
                100));
    }
    
}