/*
 * Generated by ChatGPT
 */

public sealed class ColorMathTests {

    //TODO : Réactiver
    /*
    [Fact]
    public void Clamp01_Should_Work() {
        Assert.Equal(0, ColorMath.Clamp01(-2));
        Assert.Equal(.5, ColorMath.Clamp01(.5));
        Assert.Equal(1, ColorMath.Clamp01(5));
    }
    */

    //TODO : Réactiver
    /*
    [Fact]
    public void Lerp_Should_Work() {
        Assert.Equal(
            5,
            ColorMath.Lerp(0, 10, .5));
    }
    */

    //TODO : Réactiver
    /*
    [Fact]
    public void InverseLerp_Should_Work() {
        Assert.Equal(
            .5,
            ColorMath.InverseLerp(
                10,
                20,
                15));
    }
    */

    //TODO : Réactiver
    /*
    [Fact]
    public void Remap_Should_Work() {
        Assert.Equal(
            50,
            ColorMath.Remap(
                .5,
                0,
                1,
                0,
                100));
    }
    */
}