/*
 * Generated by ChatGPT
 */

using System.Drawing;
using Xunit;

namespace ColorForge.Core.Tests;

public sealed class GammaTests {

    [Theory]
    [InlineData(0)]
    [InlineData(32)]
    [InlineData(64)]
    [InlineData(128)]
    [InlineData(192)]
    [InlineData(255)]
    public void Gamma_Roundtrip(byte value) {
        double linear =
            ColorConverter.SrgbToLinear(value);

        byte result =
            ColorConverter.LinearToSrgb(linear);

        AssertEx.NearlyEqual(value, result);
    }
    

    [Fact]
    public void Black_Should_Be_Zero() {
        AssertEx.NearlyEqual(
            0.0,
            ColorConverter.SrgbToLinear(0));
    }
    
    [Fact]
    public void White_Should_Be_One() {
        AssertEx.NearlyEqual(
            1.0,
            ColorConverter.SrgbToLinear(255),
            12);
    }
   
}