/*
 * Generated by ChatGPT
 */

using System.Drawing;
using Xunit;

namespace ColorForge.Core.Tests;

public sealed class GammaTests {

    //TODO : Réactiver
    /*
    [Theory]
    [InlineData(0)]
    [InlineData(32)]
    [InlineData(64)]
    [InlineData(128)]
    [InlineData(192)]
    [InlineData(255)]
    public void Gamma_Roundtrip(byte value) {
        var linear =
            ColorConverter.SrgbToLinear(value);

        var result =
            ColorConverter.LinearToSrgb(linear);

        Assert.Equal(value, result);
    }
    */

    //TODO : Réactiver
    /*
    [Fact]
    public void Black_Should_Be_Zero() {
        Assert.Equal(
            0.0,
            ColorConverter.SrgbToLinear(0));
    }
    */

    //TODO : Réactiver
    /*
    [Fact]
    public void White_Should_Be_One() {
        Assert.Equal(
            1.0,
            ColorConverter.SrgbToLinear(255),
            12);
    }
    */
}