/*
 * Generated by ChatGPT
 */

using ColorForge.Core;
using Xunit;

namespace ColorForge.Core.Tests;

public sealed class LinearRgbColorTests {

    [Fact]
    public void Clamp_Should_Work() {
        LinearRgbColor color = new(
            -0.2,
             0.5,
             1.4);

        LinearRgbColor result = color.Clamp();

        AssertEx.NearlyEqual(0.0, result.R);
        AssertEx.NearlyEqual(0.5, result.G);
        AssertEx.NearlyEqual(1.0, result.B);
    }
    
    [Fact]
    public void InGamut_Should_Return_True() {
        LinearRgbColor color = new(
            0.2,
            0.5,
            0.9);

        Assert.True(color.IsInGamut);
    }
    
    [Fact]
    public void InGamut_Should_Return_False() {
        LinearRgbColor color = new(
            1.2,
            0.3,
            0.5);

        Assert.False(color.IsInGamut);
    }
   
    [Fact]
    public void Equality_Should_Work() {
        LinearRgbColor a = new(0.1, 0.2, 0.3);
        LinearRgbColor b = new(0.1, 0.2, 0.3);

        Assert.Equal(a, b);
    }
   
}