/*
 * Generated by ChatGPT
 */

using ColorForge.Core;

public sealed class OklabConversionTests {

    [Fact]
    public void White_Roundtrip() {
        LinearRgbColor rgb = 
            new(
                1,
                1,
                1
            );

        OklabColor lab =
            ColorConverter.ToOklab(rgb);

        LinearRgbColor result =
            ColorConverter.FromOklab(lab);

        AssertEx.NearlyEqual(rgb, result);
    }
    

    [Fact]
    public void Red_Roundtrip() {
        LinearRgbColor rgb = new(
            1,
            0,
            0);

        OklabColor lab =
            ColorConverter.ToOklab(rgb);

        LinearRgbColor result =
            ColorConverter.FromOklab(lab);

        AssertEx.NearlyEqual(rgb, result);

    }
    
}