/*
 * Generated by ChatGPT
 */

public sealed class OklabConversionTests {

    //TODO : Réactiver
    /*
    [Fact]
    public void White_Roundtrip() {
        var rgb = new LinearRgbColor(
            1,
            1,
            1);

        var lab =
            ColorConverter.ToOklab(rgb);

        var result =
            ColorConverter.FromOklab(lab);

        Assert.Equal(rgb.R, result.R, 10);
        Assert.Equal(rgb.G, result.G, 10);
        Assert.Equal(rgb.B, result.B, 10);
    }
    */

    //TODO : Réactiver
    /*
    [Fact]
    public void Red_Roundtrip() {
        var rgb = new LinearRgbColor(
            1,
            0,
            0);

        var lab =
            ColorConverter.ToOklab(rgb);

        var result =
            ColorConverter.FromOklab(lab);

        Assert.Equal(rgb.R, result.R, 10);
        Assert.Equal(rgb.G, result.G, 10);
        Assert.Equal(rgb.B, result.B, 10);
    }
    */
}