/*
 * Generated by ChatGPT
 */

using ColorForge.Core;

public sealed class OklabConversionTests {

    [Fact]
    public void White_Roundtrip() {
        LinearRgbColor rgb = 
            new(
                1,
                1,
                1
            );

        OklabColor lab =
            ColorConverter.ToOklab(rgb);

        LinearRgbColor result =
            ColorConverter.FromOklab(lab);

        Assert.Equal(rgb.R, result.R, 10);
        Assert.Equal(rgb.G, result.G, 10);
        Assert.Equal(rgb.B, result.B, 10);
    }
    

    [Fact]
    public void Red_Roundtrip() {
        LinearRgbColor rgb = new(
            1,
            0,
            0);

        OklabColor lab =
            ColorConverter.ToOklab(rgb);

        LinearRgbColor result =
            ColorConverter.FromOklab(lab);

        Assert.Equal(rgb.R, result.R, 10);
        Assert.Equal(rgb.G, result.G, 10);
        Assert.Equal(rgb.B, result.B, 10);
    }
    
}