/*
 * Generated by ChatGPT
 */

using ColorForge.Core;
using Xunit;

namespace ColorForge.Core.Tests;

public sealed class OklabColorTests {

    [Fact]
    public void Constructor_Should_Assign_Properties() {
        OklabColor color = new(0.75, 0.15, -0.08);

        AssertEx.NearlyEqual(0.75, color.L);
        AssertEx.NearlyEqual(0.15, color.A);
        AssertEx.NearlyEqual(-0.08, color.B);
    }
    

    [Fact]
    public void IsValid_Should_Be_True() {
        OklabColor color = new(0.5, 0.1, -0.1);

        Assert.True(color.IsValid);
    }
    

    [Fact]
    public void IsValid_Should_Be_False_When_Component_Is_NaN() {
        OklabColor color = new(double.NaN, 0.0, 0.0);

        Assert.False(color.IsValid);
    }
    
    [Fact]
    public void WithLightness_Should_Create_New_Instance() {
        OklabColor original = new(0.40, 0.10, 0.20);

        OklabColor modified = original.WithLightness(0.80);

        AssertEx.NearlyEqual(0.80, modified.L);
        AssertEx.NearlyEqual(original.A, modified.A);
        AssertEx.NearlyEqual(original.B, modified.B);
    }
    

    [Fact]
    public void Equality_Should_Work() {
        OklabColor c1 = new(0.5, 0.1, 0.2);
        OklabColor c2 = new(0.5, 0.1, 0.2);

        Assert.Equal(c1, c2);
    }
    
}