/*
 * Generated by ChatGPT
 */

using ColorForge.Core;
using Xunit;

namespace ColorForge.Core.Tests;

public sealed class OklchColorTests {
    //TODO : Réactiver
/*
[Fact]
public void Constructor_Should_Normalize_Hue() {
    var color = new OklchColor(0.50, 0.20, 390);

    Assert.Equal(30, color.H);
}
*/

//TODO : Réactiver
/*
[Fact]
public void Negative_Hue_Should_Be_Normalized() {
var color = new OklchColor(0.50, 0.20, -45);

Assert.Equal(315, color.H);
}
*/

//TODO : Réactiver
/*
[Fact]
public void RotateHue_Should_Wrap_Correctly() {
var color = new OklchColor(0.40, 0.10, 350);

var rotated = color.RotateHue(20);

Assert.Equal(10, rotated.H);
}
*/

//TODO : Réactiver
/*
[Fact]
public void WithChroma_Should_Create_New_Instance() {
var original = new OklchColor(0.60, 0.15, 45);

var modified = original.WithChroma(0.30);

Assert.Equal(original.L, modified.L);
Assert.Equal(0.30, modified.C);
Assert.Equal(original.H, modified.H);
}
*/

//TODO : Réactiver
/*
[Fact]
public void Equality_Should_Work() {
var c1 = new OklchColor(0.5, 0.2, 90);
var c2 = new OklchColor(0.5, 0.2, 90);

Assert.Equal(c1, c2);
}
*/

//TODO : Réactiver
/*
[Fact]
public void IsValid_Should_Return_False_For_NaN() {
var color = new OklchColor(double.NaN, 0.2, 45);

Assert.False(color.IsValid);
}
*/
}