/*
 * Generated by ChatGPT
 */

using ColorForge.Core;
using Xunit;

namespace ColorForge.Core.Tests;

public sealed class OklchColorTests {

    [Fact]
    public void Constructor_Should_Normalize_Hue() {
        OklchColor color = new(0.50, 0.20, 390);

        Assert.Equal(30, color.H);
    }


    [Fact]
    public void Negative_Hue_Should_Be_Normalized() {
        OklchColor color = new(0.50, 0.20, -45);

        Assert.Equal(315, color.H);
    }

    [Fact]
    public void RotateHue_Should_Wrap_Correctly() {
        OklchColor color = new(0.40, 0.10, 350);

        OklchColor rotated = color.RotateHue(20);

        Assert.Equal(10, rotated.H);
    }


    [Fact]
    public void WithChroma_Should_Create_New_Instance() {
        OklchColor original = new(0.60, 0.15, 45);

        OklchColor modified = original.WithChroma(0.30);

        Assert.Equal(original.L, modified.L);
        Assert.Equal(0.30, modified.C);
        Assert.Equal(original.H, modified.H);
    }

    [Fact]
    public void Equality_Should_Work() {
        OklchColor c1 = new(0.5, 0.2, 90);
        OklchColor c2 = new(0.5, 0.2, 90);

        Assert.Equal(c1, c2);
    }

    [Fact]
    public void IsValid_Should_Return_False_For_NaN() {
        OklchColor color = new(double.NaN, 0.2, 45);

        Assert.False(color.IsValid);
    }

}