/*
 * Generated by ChatGPT
 */

using ColorForge.Core;
using Xunit;

namespace ColorForge.Core.Tests;

public class ThemeColorTests {

    [Fact]
    public void Equality() {
        ThemeColor c1 = ThemeColor.FromHex("#336699");
        ThemeColor c2 = ThemeColor.FromRgb(0x33, 0x66, 0x99);

        Assert.Equal(c1, c2);
    }
    
    [Fact]    
    public void HexFormatting() {
        ThemeColor color = ThemeColor.FromHex("#336699");

        Assert.Equal("#336699",
            color.ToRgbHex());
    }
    
    [Fact]
    public void AlphaFormatting() {
        ThemeColor color = ThemeColor.FromHex("#80336699");

        Assert.Equal("#80336699",
            color.ToArgbHex());
    }
    
    [Fact]
    public void Deconstruct() {
        ThemeColor color = ThemeColor.FromRgb(
            1, 2, 3);

        (byte r, byte g, byte b, byte a) = color;

        Assert.Equal((byte)1, r);
        Assert.Equal((byte)2, g);
        Assert.Equal((byte)3, b);
        Assert.Equal((byte)255, a);
    }
    
}