/*
 * Generated by ChatGPT
 */

using ColorForge.Core;
using Xunit;

namespace ColorForge.Core.Tests;

public sealed class XyzColorTests {

    [Fact]
    public void Constructor_Should_Assign_Values() {
        XyzColor xyz = new(
            0.32,
            0.48,
            0.19);

        Assert.Equal(0.32, xyz.X);
        Assert.Equal(0.48, xyz.Y);
        Assert.Equal(0.19, xyz.Z);
    }
    
    [Fact]
    public void Equality_Should_Work() {
        XyzColor a = new(1, 2, 3);
        XyzColor b = new(1, 2, 3);

        Assert.Equal(a, b);
    }
    
    [Fact]
    public void WithY_Should_Return_New_Instance() {
        XyzColor xyz = new(1, 2, 3);

        XyzColor modified = xyz.WithY(10);

        Assert.Equal(1, modified.X);
        Assert.Equal(10, modified.Y);
        Assert.Equal(3, modified.Z);
    }
    
    [Fact]
    public void Invalid_Value_Should_Be_Detected() {
        XyzColor xyz = new(
            double.NaN,
            0,
            0
        );

        Assert.False(xyz.IsValid);
    }
    
}