/*
 * Generated by ChatGPT
 */

using System.Drawing;

public sealed class XyzConversionTests {
    //TODO : Réactiver
    /*
    [Fact]
    public void White_Should_Convert_To_D65() {
        var linear = new LinearRgbColor(
            1,
            1,
            1);

        var xyz = ColorConverter.ToXyz(linear);

        Assert.Equal(0.950, xyz.X, 3);
        Assert.Equal(1.000, xyz.Y, 3);
        Assert.Equal(1.089, xyz.Z, 3);
    }
    */

    //TODO : Réactiver
    /*
    [Fact]
    public void Roundtrip_Should_Work() {
        var linear =
            new LinearRgbColor(
                0.2,
                0.5,
                0.8);

        var xyz =
            ColorConverter.ToXyz(linear);

        var result =
            ColorConverter.FromXyz(xyz);

        Assert.Equal(linear.R, result.R, 10);
        Assert.Equal(linear.G, result.G, 10);
        Assert.Equal(linear.B, result.B, 10);
    }
    */
}