/*
 * Generated by ChatGPT
 */

using ColorForge.Core;

public sealed class XyzConversionTests {

    [Fact]
    public void White_Should_Convert_To_D65() {
        LinearRgbColor linear = new(
            1,
            1,
            1
        );

        XyzColor xyz = ColorConverter.ToXyz(linear);

        Assert.Equal(0.950, xyz.X, 3);
        Assert.Equal(1.000, xyz.Y, 3);
        Assert.Equal(1.089, xyz.Z, 3);
    }
    
    [Fact]
    public void Roundtrip_Should_Work() {
        LinearRgbColor linear =
            new(
                0.2,
                0.5,
                0.8
            );

        XyzColor xyz =
            ColorConverter.ToXyz(linear);

        LinearRgbColor result =
            ColorConverter.FromXyz(xyz);

        Assert.Equal(linear.R, result.R, 10);
        Assert.Equal(linear.G, result.G, 10);
        Assert.Equal(linear.B, result.B, 10);
    }
   
}